
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${eureka.server.port}/eureka/
  instance:
    health-check-url-path: /actuator/health
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
feign:
  hystrix:
    enabled: true