zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    user-service:
      path: /userapi/**
      serviceId: user-service
#      sensitiveHeaders:
  sensitive-headers: Cookie,Set-Cookie
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${eureka.server.port}/eureka/
  instance:
    health-check-url-path: /actuator/health
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always